import csv, datetime

SITE = "wholenesscommunitymarketplace.com"
# (dimension, format, theme, hook, l1, l2, l3, l4, punchline, cta, stock_keywords, ai_prompt, caption, tags)
R = [
("Nutrition & Healing","Reel","Recipe","When your body says \"eat healthy\" and your brain says \"cookie\"","1 cup plain Greek yogurt","A handful of berries","1 tbsp chia or flax","Drizzle of honey + cinnamon","Tastes like dessert. Your blood sugar stays calm about it.","Take the free Wholeness Assessment",
 "woman making yogurt bowl kitchen, berries close up, woman smiling eating breakfast",
 "Bright modern kitchen, morning light. A fit woman in her 30s layers Greek yogurt, berries and chia into a white bowl, takes a bite and smiles at camera. Vertical 9:16, natural handheld feel.",
 "Your body wants healthy. Your brain wants a cookie. This bowl keeps the peace. Two minutes, no stove, tastes like dessert. Save it for your next 3pm craving.",
 "#healthyrecipes #easybreakfast #bloodsugarfriendly #nutritionandhealing"),
("Physical Wellness","Reel","Workout","The workout your boss will never notice","Chair squats, 10 reps","Overhead reach, 10 slow reps","Shoulder squeezes, 15 reps","Repeat twice","Posture so good it scares the printer.","Find a provider who builds plans around YOUR body",
 "man office chair squat, office stretching, man desk posture",
 "A fit man in his 30s in a bright open office does chair squats and overhead stretches beside his desk while coworkers work behind him, then gives a sly thumbs up to camera. Vertical 9:16.",
 "Ten minutes of sitting a little less. Your back will send you a thank-you note. Check with your doctor before starting something new, especially if you're managing a condition.",
 "#deskworkout #officefitness #movemore #physicalwellness"),
("Mind & Emotions","Reel","Humor","My brain at 2am: \"Remember that thing you said in 2011?\"","Write it down, then close the notebook","Name 5 things you can see","Breathe in 4, hold 4, out 6","Remind yourself: nobody remembers 2011","Your brain is a great employee and a terrible night manager.","Take the free Wholeness Assessment",
 "woman awake in bed at night, woman journaling bedside lamp, calm breathing",
 "A woman in her late 20s lies awake in bed, eyes wide, then sits up, writes in a journal by lamplight, exhales and smiles. Cozy bedroom, warm tones. Vertical 9:16.",
 "Overthinking at 2am is a full-time job nobody applied for. Four small things that help the brain clock out.",
 "#overthinking #mentalwellness #anxietytips #mindandemotions"),
("Stress Relief & Rest","Reel","Good habit","Your phone does not need to be the last thing you see tonight","Phone charges outside the bedroom","Lights dim an hour before bed","Same bedtime, even on weekends","A real book. Yes, paper.","Your screen time report won't know what hit it.","Join the community free",
 "woman reading book in bed, phone charging on kitchen counter, dim cozy bedroom",
 "A man in his 30s plugs his phone in on a kitchen counter, walks away, then reads a paperback in a softly lit bedroom and drifts off. Calm, warm tones. Vertical 9:16.",
 "Better sleep starts about an hour before you hit the pillow. Four swaps to try this week.",
 "#sleephygiene #bettersleep #eveningroutine #stressrelief"),
("Relationships & Support","Reel","Humor","Texting a friend \"we should catch up!\" for the 9th year in a row","Pick a day right now","Make it a walk, not dinner","Put it in both calendars","Actually show up","Friendship is a muscle. So is your thumb, apparently.","Find your people at Wholeness Community",
 "two friends walking park laughing, friends coffee outdoors, woman texting smiling",
 "Two friends in their 30s, a man and a woman, laugh while walking through a sunny park with coffee cups. Natural, candid feel. Vertical 9:16.",
 "Connection is part of health, not a bonus. Text that friend and pick a real day.",
 "#friendship #connection #relationships #socialwellness"),
("Financial Wellness","Reel","Good habit","Financial stress is health stress. Here's a 5-minute fix.","Open your bank app once a week","Cancel one subscription you forgot about","Move $10 to savings automatically","Celebrate small wins","That free trial from 2023 has been charging you rent.","Explore Financial Wellness on Wholeness Community",
 "man reviewing budget on phone kitchen, couple planning finances laptop, piggy bank",
 "A couple in their 30s sits at a kitchen table with coffee, scrolling a banking app, laughing as they cancel a subscription. Warm morning light. Vertical 9:16.",
 "Money worries show up in your sleep, your mood and your body. Five minutes a week goes a long way.",
 "#financialwellness #moneyhabits #budgeting #financialhealth"),
("Spirituality & Purpose","Reel","Good habit","The 3-minute morning that changes the whole day","1 minute of quiet","1 thing you're grateful for","1 intention for today","Then coffee","Peace first. Emails can wait. They always do.","Take the free Wholeness Assessment",
 "woman sitting quietly sunrise window, journaling gratitude, man prayer morning light",
 "A woman in her 40s sits by a sunlit window with a mug, eyes closed, then writes a single line in a journal and smiles. Soft golden light. Vertical 9:16.",
 "Three minutes. No app, no subscription, no fancy cushion. Just a better start.",
 "#morningroutine #gratitude #purpose #spiritualwellness"),
("Nutrition & Healing","Reel","Recipe","One pan. 20 minutes. Fewer dishes than your excuses.","Salmon, broccoli, sweet potato","Olive oil, garlic, lemon, salt","400F for 18 to 20 minutes","Extra lemon at the end","Takeout is nervous right now.","Find nutrition support on Wholeness Community",
 "sheet pan salmon vegetables oven, man cooking dinner kitchen, family eating dinner",
 "A man in his 30s slides a sheet pan of salmon, broccoli and sweet potato into an oven, then serves it to smiling friends at a table. Warm home kitchen. Vertical 9:16.",
 "Omega-3s, fiber and a clean kitchen. Dinner done before your show starts.",
 "#sheetpandinner #easydinner #salmonrecipe #antiinflammatory"),
("Physical Wellness","Reel","Workout","Commercial break workout, for people who refuse to miss the show","Break 1: jumping jacks or low-impact steps","Break 2: couch squats, 12 reps","Break 3: march in place","Repeat every break","Touch the cushion. Do not sit. Don't you dare.","Join the community free",
 "woman workout living room tv, couch squats home, woman marching in place",
 "A woman in her 30s in a cozy living room jumps up during a TV commercial, does squats touching the couch cushion, then flops back down laughing. Vertical 9:16.",
 "Every bit of movement counts. Go at your own pace and listen to your body.",
 "#homeworkout #couchworkout #lowimpact #movemore"),
("Conditions & Recovery","Reel","Encouragement","Living with a chronic condition? You're not lazy. You're managing a lot.","Rest is part of the plan","Good days and bad days both count","Ask for help before you need it","Find people who get it","You don't have to earn rest.","Join a community that understands",
 "woman resting couch blanket tea, support group circle, man smiling recovery walk",
 "A woman in her 40s rests on a couch with tea and a blanket, then later laughs with a small, supportive group of friends in a sunny living room. Warm, gentle tones. Vertical 9:16.",
 "Chronic conditions come with invisible work. This community was built for exactly that.",
 "#chronicillness #chronicillnesssupport #spoonie #recoveryjourney"),
("Home & Lifestyle","Reel","Humor","Me: I'll just tidy for 5 minutes. Also me, 3 hours later:","Set a 10-minute timer","One surface only","Put things back, don't reorganize","Stop when it rings","A clear counter is basically therapy with fewer forms.","Explore Home & Lifestyle",
 "woman tidying kitchen counter, clean organized home, man folding laundry smiling",
 "A man in his 30s sets a kitchen timer, quickly clears one countertop, wipes it down and admires it proudly. Bright, airy kitchen. Vertical 9:16.",
 "Your space affects your stress. Ten minutes, one surface, done.",
 "#tidyhome #homelifestyle #declutter #calmhome"),
("Nutrition & Healing","Reel","Recipe","The snack that ends the 3pm vending machine walk","Apple slices","2 tbsp peanut or almond butter","Sprinkle of granola","Pinch of cinnamon","Crunchy, sweet, and nobody gets a sugar crash.","Take the free Wholeness Assessment",
 "apple slices peanut butter snack, woman eating snack office, healthy snack plate",
 "A woman in her 20s at a sunny desk spreads almond butter on apple slices, sprinkles granola and takes a crunchy bite. Clean, bright light. Vertical 9:16.",
 "Fiber plus protein means steady energy. The vending machine will miss you.",
 "#healthysnacks #afternoonsnack #snackideas #nutrition"),
("Physical Wellness","Reel","Workout","A 10-minute walk after dinner does more than you think","Helps with blood sugar after meals","Eases digestion","Clears your head","Bonus: neighborhood gossip","The couch will still be there. Promise.","Find a provider on Wholeness Community",
 "couple walking evening neighborhood, man walking dog sunset, family walk after dinner",
 "A couple in their 40s walks through a tree-lined neighborhood at sunset, chatting and laughing. Golden hour, relaxed feel. Vertical 9:16.",
 "A short walk after meals is one of the easiest habits you can build. Bring someone along.",
 "#walking #afterdinnerwalk #bloodsugar #healthyhabits"),
("Mind & Emotions","Reel","Good habit","Three words that lower stress fast: \"Not right now.\"","Saying no is self-care","You can't pour from an empty cup","Protect your calendar","Guilt is optional","\"No\" is a complete sentence. Practice it in the mirror.","Take the free Wholeness Assessment",
 "woman confident smiling office, man relaxing park bench, calendar planning",
 "A confident woman in her 30s politely declines a meeting on a video call, closes her laptop and steps outside into the sun, smiling. Vertical 9:16.",
 "Boundaries protect your energy. Your energy protects your health.",
 "#boundaries #mentalhealth #selfcare #stressmanagement"),
("Stress Relief & Rest","Reel","Good habit","Box breathing: the 60-second reset","Breathe in for 4","Hold for 4","Breathe out for 4","Hold for 4, repeat","Free, takes a minute, and nobody can tell you're doing it.","Join the community free",
 "man breathing calm eyes closed, woman meditation office, calm nature",
 "A man in his 30s at a busy desk pauses, closes his eyes, breathes slowly, and his shoulders visibly relax. Soft focus background. Vertical 9:16.",
 "Use it before a meeting, in traffic, or before a tough conversation.",
 "#boxbreathing #breathwork #stressrelief #calm"),
("Relationships & Support","Reel","Encouragement","Caregivers: who's taking care of you?","Ask for one specific favor","Take 20 minutes just for you","Join a caregiver group","Say yes when people offer","You can't fill anyone's cup from an empty pitcher.","Find caregiver support on Wholeness Community",
 "caregiver woman with elderly parent, woman tea break peaceful, support group caregivers",
 "A woman in her 40s helps her elderly father to a chair, then steps onto a porch with tea for a quiet moment and smiles. Warm, tender tones. Vertical 9:16.",
 "Caregiving is love and work. You deserve support too.",
 "#caregiver #caregiversupport #selfcare #familycaregiver"),
("Nutrition & Healing","Reel","Recipe","Breakfast for people who are late. Always.","Overnight oats: 1/2 cup oats","1/2 cup milk, 1/4 cup yogurt","Chia, berries, cinnamon","Fridge overnight, grab and go","Past you just saved present you. Hero stuff.","Take the free Wholeness Assessment",
 "overnight oats jar, man grabbing breakfast fridge rushing, mason jar breakfast",
 "A man in his 30s in a dress shirt rushes into a kitchen, grabs a mason jar of overnight oats from the fridge, winks at camera and heads out. Vertical 9:16.",
 "Five minutes the night before. Zero excuses in the morning.",
 "#overnightoats #mealprep #easybreakfast #healthybreakfast"),
("Physical Wellness","Reel","Workout","Stretch with me, it's 3 minutes and your hips will thank you","Neck rolls, 30 seconds","Shoulder rolls, 30 seconds","Hip circles, 1 minute","Forward fold, 1 minute","Your hips have been sitting through every meeting with you.","Find a provider on Wholeness Community",
 "woman stretching living room morning, hip stretch, yoga mat home",
 "A woman in her 30s in athletic wear stretches on a mat in a bright living room, doing neck rolls and a forward fold, then grins at camera. Vertical 9:16.",
 "Gentle movement, no equipment. Modify anything that doesn't feel right.",
 "#stretching #mobility #morningstretch #gentlemovement"),
("Financial Wellness","Reel","Humor","Me: \"I'm saving money.\" Also me: \"$7 coffee, every day.\"","Track spending for 1 week","Find your top 3 money leaks","Fix just one","Keep the joy spending","Budget for the coffee. Just don't let the coffee run the budget.","Explore Financial Wellness",
 "woman buying coffee cafe, man checking bank app surprised, coffee at home",
 "A woman in her 20s happily buys a fancy coffee, then checks her banking app and does a dramatic double take. Playful, bright cafe. Vertical 9:16.",
 "Financial wellness isn't about never treating yourself. It's about knowing where it all goes.",
 "#moneytips #budgetingtips #financialwellness #savingmoney"),
("Spirituality & Purpose","Reel","Encouragement","Your purpose doesn't have to be big to be real","Show up for one person","Do one thing you're good at","Notice what gives you energy","Do more of that","Small purpose is still purpose. Ask any grandma.","Take the free Wholeness Assessment",
 "volunteer helping community, grandmother teaching baking, man mentoring youth",
 "A man in his 40s helps neighbors at a community garden, handing over vegetables and laughing. Sunny, warm tones. Vertical 9:16.",
 "Purpose lives in small, daily things. Look for what lights you up.",
 "#purpose #meaningfullife #spiritualwellness #community"),
("Conditions & Recovery","Reel","Good habit","Going to a doctor's appointment? Bring this list.","Your symptoms and when they started","Every med and supplement you take","Your top 3 questions","Someone to take notes","Doctors love an organized patient. It's basically flirting.","Get organized with Wholeness Community resources",
 "woman doctor appointment notes, patient talking doctor, notebook list",
 "A woman in her 40s sits in a bright clinic waiting room reviewing a handwritten list, then talks confidently with a doctor. Clean, calm tones. Vertical 9:16.",
 "A little prep turns a rushed appointment into a real conversation.",
 "#doctorsappointment #patientadvocacy #chronicillness #healthtips"),
("Home & Lifestyle","Reel","Good habit","Your home can lower your stress. Start here.","Open the curtains first thing","Add one plant","Clear the entryway","Play music while you cook","Plants: the only roommate who never eats your leftovers.","Explore Home & Lifestyle",
 "woman opening curtains sunlight, houseplants living room, man cooking music",
 "A woman in her 30s opens curtains to flood a living room with sunlight, waters a plant, and dances a little while cooking. Bright, joyful. Vertical 9:16.",
 "Small changes to your space change how you feel in it.",
 "#homedecor #calmhome #plants #homelifestyle"),
("Mind & Emotions","Reel","Humor","Things that are not emergencies:","An email marked \"urgent\"","A group chat with 47 messages","Your phone at 12% battery","A meeting that could've been an email","Breathe. Most \"fires\" are just smoke alarms with good PR.","Take the free Wholeness Assessment",
 "man calm ignoring phone notifications, woman relaxed coffee, office humor",
 "A man in his 30s calmly sips tea while his phone buzzes nonstop on the desk, then flips it face down and smiles. Bright office. Vertical 9:16.",
 "Not everything deserves your adrenaline. Save it for the real stuff.",
 "#stressless #mentalwellness #workstress #perspective"),
("Nutrition & Healing","Reel","Recipe","The 5-minute lunch that beats the drive-thru","Can of chickpeas, rinsed","Cucumber, tomato, red onion","Olive oil, lemon, salt, oregano","Feta if you're feeling fancy","Fiber, protein and zero waiting in line.","Find nutrition support on Wholeness Community",
 "chickpea salad bowl, woman making salad kitchen, mediterranean lunch",
 "A woman in her 30s tosses a colorful chickpea salad in a big bowl, adds feta, and takes a bite at a sunny kitchen counter. Vertical 9:16.",
 "Mediterranean, no cooking, and it keeps in the fridge for days.",
 "#chickpeasalad #healthylunch #mediterraneandiet #mealprep"),
("Physical Wellness","Reel","Workout","No gym? No problem. 4 moves, 8 minutes.","Wall push-ups, 10","Glute bridges, 12","Step-ups on a stair, 10 each","Plank, 20 seconds","Your living room just became a gym. Rent's the same.","Find a provider on Wholeness Community",
 "man home workout wall pushups, glute bridge mat, stair step ups",
 "A fit man in his 30s does wall push-ups, glute bridges and step-ups at home, then wipes his brow and grins. Bright, modern home. Vertical 9:16.",
 "Strength training at home, beginner-friendly. Modify as needed.",
 "#homeworkout #strengthtraining #beginnerworkout #noequipment"),
("Stress Relief & Rest","Reel","Humor","Rest is not a reward. Here's your permission slip.","Nap without guilt","Sit outside for 10 minutes","Say no to one thing","Do absolutely nothing","Signed, your nervous system.","Join the community free",
 "woman napping hammock, man sitting outside relaxing, peaceful backyard",
 "A woman in her 30s lies in a backyard hammock with sunglasses, sighs contentedly and waves lazily at the camera. Golden afternoon. Vertical 9:16.",
 "You don't have to earn rest. It's part of being healthy.",
 "#rest #selfcare #slowliving #stressrelief"),
("Relationships & Support","Reel","Good habit","The 2-minute habit that makes relationships stronger","Ask \"how are you really?\"","Put the phone down","Listen without fixing","Say thanks for something small","People don't need advice. They need you to stop looking at your phone.","Find your people at Wholeness Community",
 "couple talking kitchen phones down, friends deep conversation, man listening smiling",
 "A couple in their 30s puts their phones face down on the kitchen table and talks over coffee, laughing. Warm, natural light. Vertical 9:16.",
 "Good relationships are good health. Two minutes of real attention counts.",
 "#relationships #connection #communication #socialwellness"),
("Financial Wellness","Reel","Good habit","Building financial security? Start with this.","Emergency fund goal: 1 month of bills","Automate it on payday","Keep it in a separate account","Don't touch it for vacations","Future you is already sending a thank-you card.","Explore Financial Wellness",
 "man smiling savings app, couple budget coffee table, payday celebration",
 "A man in his 30s sets up an automatic transfer on his phone, then fist-pumps quietly at his kitchen table. Morning light. Vertical 9:16.",
 "A small emergency fund is one of the biggest stress reducers there is.",
 "#emergencyfund #financialsecurity #savingstips #financialwellness"),
("Conditions & Recovery","Reel","Encouragement","Progress isn't a straight line. It's more like a toddler's drawing.","Some days are steps back","That's still progress","Track the good days too","Tell someone about your wins","Messy progress is still progress.","Join a community that understands",
 "woman physical therapy recovery smiling, man walking recovery park, celebrating small win",
 "A man in his 40s walks slowly but steadily through a park with a cane, then stops to smile and high-five a friend. Warm, hopeful light. Vertical 9:16.",
 "Healing doesn't follow a schedule. Celebrate every bit of it.",
 "#recovery #healingjourney #chronicillness #progressnotperfection"),
("Mind & Emotions","Reel","Community","30 days of small steps. What's yours?","Water before coffee","Walk after dinner","Phone out of the bedroom","One real conversation","The best habit is the one you'll actually keep.","Take the free Wholeness Assessment",
 "diverse group friends laughing outdoors, people walking together, community gathering",
 "A diverse group of adults in their 30s and 40s laugh together at an outdoor picnic in a sunny park. Joyful, candid. Vertical 9:16.",
 "Thirty days of small steps. Tell us which one stuck for you in the comments.",
 "#smallsteps #healthyhabits #wellnesscommunity #wholepersonhealth"),
]

BASE = "#wholepersonwellness #wholenesscommunity #wellnessjourney"
start = datetime.date(2026, 10, 9)
cols = ["Day","Date","Weekday","Post time (ET)","Dimension","Format","Theme","Hook","Line 1","Line 2","Line 3","Line 4",
        "Punchline","CTA","Website","Stock video search terms","AI video prompt (Veo / Kling / Runway)","Caption","Hashtags"]
with open("out/wcm_30_day_content_calendar.csv", "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f); w.writerow(cols)
    for i, r in enumerate(R):
        d = start + datetime.timedelta(days=i)
        wk = d.weekday() >= 5
        dim, fmt, theme, hook, l1, l2, l3, l4, punch, cta, stock, ai, cap, tags = r
        caption = f"{cap}\n\n{cta} at {SITE} (link in bio)."
        w.writerow([i + 1, d.isoformat(), d.strftime("%a"), "9:45 AM" if wk else "11:45 AM", dim, fmt, theme, hook, l1, l2, l3, l4,
                    punch, cta, SITE, stock, ai, caption, tags + " " + BASE])
print(len(R))
